### ISSUE TITLE
How do i manage references?

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#10]
Hi i have another question:
How do i manage references?
If i have two schemas and i reference one of the to the other, how to do i insert data to them?
Do i have to insert in both (and give the id of the "second" db to the first) or is it sufficient if i just insert the data into the "main" schema and insert the data of the refrenced element like the schema of the "second" db is built (as an object)?
f.e.
export class CalendarEventModel { name="CalendarEvent" props={Id: "int", Title: "string", Start: "datetime", End: "datetime", Calendar: "#Calendar"};
const CalendarSchema = {name: "Calendar", props: {Id: "int", Title:"string", Color:"string"}};
1.
Calendar.insert({Id: 1, Title:"CalendarExample", Color:"#FFFFFF"});
CalendarEvents.insert({Id: 1, Title: "example", Start: Moment(), End: Moment().add(5, "minutes"), Calendar: 1});
2. 
CalendarEvent.insert({Id: 1, Title: "example", Start: Moment(), End: Moment().add(5, "minutes"), Calendar: {Id: 1, Title:"CalendarExample", Color:"#FFFFFF"}});

And which types does datetime take (only date() of js or also Moment.js objects)?

Thank you!

**Comment by hieunc229** [comment]
Hi @apppro123 

1. It will need 2 inserts, for `Calendar` and `CalendarEvents`. Besides, Vasern will automatically create an `id` (lowercase) field.
_(P/s: Custom id has not available yet, you won't need `ID` in your schema)_

    **Here is an example, with adding reference object:**
    ```javascript
    var insertedCalendars = Calendar.insert({ Title:"CalendarExample", Color:"#FFFFFF" });

    // Calendar.insert will return an array of objects will be inserted into database with generated id. 
    // For example:
    // insertedCalendars = [
    //     { id: 'a_random_unique_id', Title: "CalendarExample", Color:"#FFFFFF" }
    // ]

    var insertedEvents = CalendarEvents.insert({ 
        Title: "example",
        Start: startTime,
        End: endTime,
        Calendar: insertedCalendars[0] // or insertedCalendars[0].id - reference by `id` or actual object
    });
    ```

2. Property with `datetime` will takes either a `Date` object or a time value in milliseconds. If you use `Momentjs`, I think you can you `.valueOf()` to get time in milliseconds. Though, `datetime` is not timezone aware.

**Comment by apppro123** [comment]
You have used insertedCalendas[0] in insertedEvents under Calendar: Is it possible to insert objects? Or is it just possible to insert insertedCalendars[0].id?

**Comment by apppro123** [comment]
Thank you first.
So is it  possible to insert an object into an element of the db? I just need one Calendar for one event.

And ty for the tip with lowercase characters.

**Comment by hieunc229** [comment]
Yes, you can pass either a `Calendar` object or its `id` to `CalendarEvents` as 
```javascript
// it will automatically get and replace the `id` from `insertedCalendars[0]`
Calendar: insertedCalendars[0] 
```

**Comment by apppro123** [comment]
Ok thanks!

**Comment by hieunc229** [comment]
No worries!

**Comment by hieunc229** [comment]
I will close this issue since it has been resolved. Also, feel free to reopen or create a new one again
