### ISSUE TITLE
Customisable id

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#11]
Is it possible to make own ids (otherwise i would just overwrite the id with my own one and save the last id with async storage)? Because i would need ascending ids, so i know that every id is only once used and 100% unique!

**Comment by hieunc229** [comment]
At the moment, the ID is highly unique.

In the ID contains different “meaningful” variables and numbers (encoded to characters), which include:
(1). Time in seconds counting from 1/1/1970
(2). A number starting from 0, if the multile ids generated in the same (1), this number will be automatically increase.
(3). 5 random characters to ensure even (2) is repeated, it still generates a different id.

Besides, the ID also design to ensure uniqueness incase it is sync to multiple devices.

Int ID is not preferable as in case it need to sync to another device, it will cause issues with duplicates id.

By the way, there is no way to generate ID that is 100% unique. Any ID generator techniques are trying to make it [super hard to duplicate](https://stackoverflow.com/questions/1155008/how-unique-is-uuid).

So you don’t really to worry about the ID uniqueness.

Is there any other reason that you need an integer id? I’ll see if I can help!

**Comment by hieunc229** [comment]
No worries. It does makes sense to me that customisable IDs is more preferable.
