### ISSUE TITLE
insert not work

### ISSUE THREAD

**Issue by GuranAmbal** [vasern/vasern#113]
Hello, for some reason I can not enter data into the database.
Viewed.insert({
      id_lectures: id
    });
I get the following error
 WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: previousCommitedItems.concat is not a function. (In 'previousCommitedItems.concat(_this8._commitedItems[key])', 'previousCommitedItems.concat' is undefined)
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.appMobileVedaRN:223709:70
forEach@[native code]

**Comment by GuranAmbal** [comment]
I'm developing on mac m1, and I'm trying to run everything on an emulator for ios

**Comment by GuranAmbal** [comment]
Now I seem to have found the reason, I had a library conflict

**Comment by hieunc229** [comment]
Welcome, @GuranAmbal. Please note that the project has been inactive for sometimes and might have issue with the current version of RN
