### ISSUE TITLE
committed transaction list

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#13]
I saw that there is a way to improve the speed of multiple actions.
Is it also faster if i don't commit these actions in a callback block but multiple single actions with save=false?
And if so, when do these actions get executed? (I mean how does the db know when i make the last action?)
I'm asking this because i have to add multiple events to the db. In one cycle i add to multiple schemas so i just want to call my "normal" saveEvent function (which normally just saves one event with save=true) with save=false. But is this faster?

**Comment by hieunc229** [comment]
Have you tried the [perform](https://vasern.com/docs/basic-crud-operation#perform-multiple-operations) block? It is somewhat similar to your idea and is designed to execute multiple operations (insert/update/remove).

Operations within the `perform` block will be called with `save=false`. When `save=false`, the record will be added to the commit transaction list, then later be executed by calling `save()` method.

**Comment by apppro123** [comment]
Then i can call after the looped finished and so i made all the inserts with save=false the method save() and it saves all the inserts, removes or updates?
If so it is possible that you forgot to mention this on your vasern website (or maybe i just dont find it...).

**Comment by hieunc229** [comment]
Actually, setting save=false for any operation is intended for internal use only. So I consider not adding it to the documentation.

Do you think it would be more useful to set save=false rather than using with the “perform” block?

It’s kinda make sense for me it can be more useful in some cases.

**Comment by apppro123** [comment]
At the moment in my case i think it is useful because i have multiple refrences and so i have to insert for every loop session into multiple schemas and insert these results into the final schema.
I think if you have to loop and insert into multiple schemas and need the results it is useful  and makes more sens then the perform() functions because otherwise you have perform( perform() perform()) or sth like that and that doesn't look nice.
In my opinion it makes sense to add this!

**Comment by hieunc229** [comment]
You’re right. It will be more useful in some cases. I’ll reconsider adding operation with “save=false”.

Thanks for the suggestion.

**Comment by apppro123** [comment]
So it is not yet possible to insert with save=false and after loop to call save() ?

**Comment by hieunc229** [comment]
Yes, it is possible! Here is an example:

```javascript

Items.insert({ name: “Item 1” }, false);
Items.insert({ name: “Item 2”}, false)

// Apply changes
Items.save()
```

**Comment by apppro123** [comment]
Perfekt!
Not related with that, but in this example you just wrote false instead of save=false. Is that possible?

**Comment by hieunc229** [comment]
It doesn’t need to actually have “save=fase”. Just “false” is correct.

**Comment by hieunc229** [comment]
I will close this issue since it has been resolved. Also, feel free to reopen or create a new one again
