### ISSUE TITLE
When trying to archive in XCode, I get "no such file - libVasern.a"

### ISSUE THREAD

**Issue by dgoenka** [vasern/vasern#15]
I'm trying archive my React Native project in XCode which has Vasern integrated. I had followed all steps as mentioned in the guide, and had no problems while developing. But now, when I try to archive my project I keep getting an error saying "no such file or directory -  <some path>/libVasern.a". Again, I can assure you that  Vasern.xcodeproj is added to my Libraries and libVasern.a is added in the Build Phrases > Link Binary with Libraries.

**Comment by hieunc229** [comment]
Hi @dgoenka, please try to delete Derived Data by go to 

1. From top menu `File -> Project Settings`, then click on the right arrow icon right next to the DerivedData directory
2. Delete the folder name that matches your app bundle id. For example DerivedData/com.app.example
3. Close xCode and restart

I try to create and archive the project and had the same issue. Then I try the solution found on https://github.com/ivpusic/react-native-image-crop-picker/issues/21#issuecomment-238794683. It worked for me.

**Comment by hieunc229** [comment]
Hi @dgoenka, please try to delete Derived Data by go to

1. From top menu File -> Project Settings, then click on the right arrow icon right next to the DerivedData directory
2. Delete the folder name that matches your app bundle id. For example DerivedData/com.app.example
3. Close xCode and restart

I ran into the issue once and the solution found this solution worked. Source: https://github.com/ivpusic/react-native-image-crop-picker/issues/21#issuecomment-238794683
