### ISSUE TITLE
Support Android platform

### ISSUE THREAD

**Issue by anhtuank7c** [vasern/vasern#2]

**Comment by hieunc229** [comment]
"Support for Android" has been added as a milestone, and I'll be working on it soon :)

**Comment by hieunc229** [comment]
I have pushed a new version of Vasern which added support for Android. Also, I am preparing a blog post in Vietnamese to introduce Vasern to the Vietnamese React Community. 

I'll close this issue and mark Support for Android millstone as completed. Feel free to reopen or create a new issue if needed.
