### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by curtisy1** [vasern/vasern#20]
Would you be willing to add typings for Typescript to this project? If you don't mind, I'll try working on getting these to work while integrating vasern in my project.

**Comment by hieunc229** [comment]
@curtisy1 Hi Alex, I do plan to add Typescript to this project. Though I won't be able to do it at this moment as I am focusing on developing its server.

In case you want to add Typescript into the project, I'd really appriciate it.
Let me know and be willing to help.

**Comment by curtisy1** [comment]
Alright, I'll start working on this today and submit a WIP pull request once I have some typings going so you can make comments on eventual coding guidelines I should adhere to

**Comment by hieunc229** [comment]
Great @curtisy1, thank you!

**Comment by hieunc229** [comment]
Hi @curtisy1, in case you need any help, please let me know. Or send me a message through [our slack channel](https://join.slack.com/t/vasern/shared_invite/enQtNDU4NTk2MDI5OTcyLTRiYzRjZDI5YTAyMjlhYzg1YTdhNjFjZGNkODI1OTQwYzExZjA3NWRkYTY1MGE2ZjU0YzU3NzE2NzUwZmEwMjM). I'm on Slack pretty often.

Cheers!

**Comment by curtisy1** [comment]
Sure thing! I'm almost done with the typings. Just need to iron out some conditions that I'm not quite sure about by testing each feature in an example database. I'll definitely contact you through Slack when I have questions.

**Comment by hieunc229** [comment]
Nice works @curtisy1. I have also added you as [our contributors](https://github.com/vasern/vasern/blob/master/README.md#contributors).

Since it is added to the repo, I'll close this issue and feel free to open again or create a new issue

Thanks a lot!
