### ISSUE TITLE
Update throw immutable error

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#22]
Error: 

You attempted to set the key `DefaultCalendar` with the value `true` on an object that is meant to be immutable and has been frozen. 

code:

export const changeCalendar = async (id, title, color) => {
    try{
        let newCalendar = await Calendar1.update(id, {id: id, Title: title, Color: color}, true);
        return newCalendar
    }catch(e){
        return e;
    }
}

**Comment by hieunc229** [comment]
There is one small issue in the code, which you can't change the `id` of the record since it the primary key. In this case, the `id` will automatically be removed. Also, you don't need to pass `true` in the 3rd argument since it was the default. You should use `Calendar1.update(id, {Title: title, Color: color});` instead.

Besides, the issue might come from from another place. The error message indicate that the document `DefaultCalendar` value has been updated. But any `Document` has been frozen to prevent developer update the value.

Is there any part of the code trying to update `DefaultCalendar`? (You might look for something like `DefaultCalendar =` in the code)

**Comment by apppro123** [comment]
Oh sorry i just see that it is the false code snippet for this error.

It should be this:
            let newCalendarId = newCalendar.id;
        let oldCalendar = await Calendar1.get({DefaultCalendar: true});
        if(newCalendarId != oldCalendar.id){
            //old default calendar
            await Calendar1.update(oldCalendar.id, {DefaultCalendar: false}, false);
            await Calendar1.update(newCalendarId, {DefaultCalendar: true}, false);
            Calendar1.save();
        }

And the error is already fired after the first Calendar1.update

**Comment by hieunc229** [comment]
I can't seem to find where the problem comes from. Can you post a screenshot of the error?

**Comment by apppro123** [comment]
Error: You attempted to set the key `DefaultCalendar` with the value `false` on an object that is meant to be immutable and has been frozen.
Error: You attempted to set the key `DefaultCalendar` with the value `false` on an object that is meant to be immutable and has been frozen.
    at throwOnImmutableMutation (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:2775:11)
    at blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:125477:26
    at Array.forEach (<anonymous>)
    at Document.update (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:125467:29)
    at CalendarsS._callee$ (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:154110:73)
    at tryCatch (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:21610:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:21785:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:21653:23)
    at tryCatch (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:21610:19)
    at invoke (blob:http://localhost:8081/3fcd1297-c359-43f3-88a6-e018552f7469:21686:22)

**Comment by hieunc229** [comment]
Thanks for the error log, I found the issue. I'll do some checking and will push an update soon

**Comment by hieunc229** [comment]
_Strangely the error didn't happen on my machine (for both RN 0.57 and 0.58)._

I have pushed an update (version 0.2.96) for the fix. You can update and don't forget to restart clean up the cache. Let me know if the error still persists.

**Comment by apppro123** [comment]
I figured it out! 
I think it was not event a mistake with vasern but rather with redux.
At the beginning i set the calendar in redux state and than took calendar.id from redux. But if i just save the id in redux and take this id it is working without mistakes!
Does redux make the objects immutable or unusable???
But thank you for your support and fast help!

**Comment by hieunc229** [comment]
Oh right, that explains why I didn’t receive the error.

Thanks for the update. I’ll close the issue and feel free to reopen it
