### ISSUE TITLE
libVasern.a not generated on a Release build

### ISSUE THREAD

**Issue by kevingalvez-pro** [vasern/vasern#27]
Debug build generates the libVasern.a file but not with Release Configuration.
If I copied generated libVasern.a file from Debug folder to Release folder it complains about invalid signing bitcode .

Yes, I did try deleting the DerivedData folder but I still can't compile a release build.

**Comment by hieunc229** [comment]
Hi Kevin, can you take a screenshot of the error? Also, are you using Xcode?

**Comment by kevingalvez-pro** [comment]
![screen shot 2019-03-06 at 5 58 00 pm](https://user-images.githubusercontent.com/38337405/53885977-f77de200-4059-11e9-97f5-6604ed393c1a.png)

Yes I'm using XCode, this is in Release config and I copied over the generated libVasern.a file from Debug to Release (because it can't generate in release)

**Comment by kevingalvez-pro** [comment]
Tried to make a release build and same error:
"clang: error: no such file or directory: '/Users/******/Library/Developer/Xcode/DerivedData/******-*********/Build/Products/Release-iphoneos/libVasern.a'"

**Comment by hieunc229** [comment]
Sorry for my late response Kevin, I've been a bit busy.

Can you make sure these following details:
1. The `libVasern.a` is present in `Build Phase > Link Binary with Libraries`
2. If you're using the `New Build System`, change it to the `Legacy Build System` as it sometimes doesn't compatible. Also select `Derived Data` as `Project-relative...` (option locate at `File > Project (or Workspace) Settings`)

After that, just `Clean up` to make sure everything is removed then `Build` again. Let me know if the issue still persist

**Comment by kevingalvez-pro** [comment]
Hi, I haven't tried this yet, I reverted to realm for now as I needed to upload a build. I'll close this for now. Thanks.

**Comment by kevingalvez-pro** [comment]
Getting this on Legacy Build System.

ld: library not found for -lVasern
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hieunc229** [comment]
Kevin, I'm unable to figure out what went wrong. If you have some time, head in the slack channel and have a chat with me. I'll try to see what went wrong ([link to slack channel](https://join.slack.com/t/vasern/shared_invite/enQtNDU4NTk2MDI5OTcyLTRiYzRjZDI5YTAyMjlhYzg1YTdhNjFjZGNkODI1OTQwYzExZjA3NWRkYTY1MGE2ZjU0YzU3NzE2NzUwZmEwMjM))

**Comment by apppro123** [comment]
I get the same problem! 
I dont know if the problem is under HeaderSearchPaths (i dont know what to write in there for vasern, with the react-native link vasern it doesnt work).
But i just get it when i do Produkt=>Archive.

**Comment by apppro123** [comment]
I have recognized that when i archive my app it doesnt add Vasern.build under IntermediateBuildFilePath and it doesnt add libVasern.a under Release-Iphoneos!
But i have no clue why i doesnt!

**Comment by apppro123** [comment]
I have solved the issue!

I have set my deployment target from 8.0 to 11.1. I think that vasern needs a higher deployment target and that was causing the problem.

**Comment by hieunc229** [comment]
Thanks @apppro123, that might be the solution. In case anyone runs into the problem, try update development target (https://github.com/vasern/vasern/issues/27#issuecomment-478377319)
