### ISSUE TITLE
key in props setting to null

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#28]
It is not quite an issue.
If i for example insert data and i set one of the key in props to null it first gives back the whole object with key value null (or undefined), but if i then reload the app, all the key set to null or undefined now have the value "". 
I would prefer if these keys would not be defined then having a string like that "".

Thank you for your response!

**Comment by hieunc229** [comment]
Hi Noah, thanks for bringing this up.

I am aware of the case. At the moment, data is saved as strings in the data file, it might be an issue when using null vs empty string (""). For example it could lead to issue similar to https://github.com/vasern/vasern/issues/14.

One little hack is you can define your own rule and check it. For example, you can save property value as a string ("null") then when load it, check if prop === "null".

It is a limitation of this version, I will see what's best and make an improvement for this case
