### ISSUE TITLE
Add documentation: do not create props with name "id" !!! related to issue #10

### ISSUE THREAD

**Issue by AsadSaleh** [vasern/vasern#29]
Thanks for this awesome library, loved this library so far. 

I just want to add a thing to your documentation, a thing that had made me took hours to resolve, which is DO NOT NAME YOUR PROPS "id" as it will lead to bug such as missing data or obfuscated key-value pairs. This happens because I put "id" as my props and my data gone crazy. To resolve this, I create a prop named "bookId" instead.

I think this should be documented in either "Supported Data Types" or "Write Schema, Setup Vasern" sections. 

Thanks in advance

**Comment by hieunc229** [comment]
Hi @AsadSaleh, thanks for bringing this up. I'll add a warning into the documentation

**Comment by hieunc229** [comment]
I have added a warning message into Vasern Website ([link](https://vasern.com/docs/write-schema-setup-vasern)). Thanks, @AsadSaleh again.

I'll go ahead and close this thread, feel free to reopen or create a new thread :)
