### ISSUE TITLE
set a key to null

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#30]
Is it possible to set a key to null or do i have to set it to null with "" ?

(if you saw old issue text, sorry, i have found the issue myself, but im still interested in this question)

Thank you!

**Comment by hieunc229** [comment]
Hey Noah, I'm assuming that you mean to set a property of the record to null. At this version, either property is set to `null`, `undefined` or `an empty string`, you will receive `an empty string` (for the property with `string` type, or `false` with boolean type).

Besides, if you mean to set a key (as the `id`) to the record, it will ignore the change
