### ISSUE TITLE
Inconsistent key name when using references

### ISSUE THREAD

**Issue by tadeolinco** [vasern/vasern#33]
There seems to have an inconsistent behavior when fetching some Documents with references in them. Some times the Document would return a reference ID with a suffix of `_id` (this is what I'm expecting), some times there would be no suffix, just whatever the Document's name is.

I see the latter more often when inserting new records into the Document.

**Comment by hieunc229** [comment]
Hi @tadeolinco, thanks for reporting the issue. I'll check it out and fix it as soon as possible

**Comment by hieunc229** [comment]
@tadeolinco Hi Sam, I couldn't find out the exact problem. My guess, the problem happens when the data haven't fully loaded, so it shows data inconsistently. Which can be avoided within [`onLoaded` method](https://vasern.com/docs/event-listeners#onloaded-event)

Can you make a snipped code about the issue? I can dig more about the issue.

**Comment by tadeolinco** [comment]
```javascript
// Post.js
class PostModel {
  name = 'Post';

  props = {
    name: 'string',
    comments: '[]#Comment',
  };
}

export default PostModel;

```
```javascript
// Comment.js
class CommentModel {
  name = 'Comment';

  props = {
    name: 'string',
    post: '#Post',
  };
}

export default CommentModel;

```

```javascript
// index.js
import Vasern from 'vasern';
import CommentModel from './models/Comment';
import PostModel from './models/Post';

const vasern = new Vasern({
  schemas: [CommentModel, PostModel],
  version: 1,
});

const { Post, Comment } = vasern;

Comment.onLoaded(() => {
  // check these values after we've inserted a comment
  console.log(Comment.data());
  /** After insertion of first comment and probably reloading the app,
   * this will print something like this: 
   * [
   *   { 
   *      name: 'sample comment',
   *      post_id: '<whatever_id_was_used>' 
   *   }
   * ]
   */
});

Comment.onChange(({ event, changed }) => {
  // check value of newly inserted comment
  if (event === 'insert') {
    console.log(changed[0]);
    /** This will print something like this:
     * {
     *    name: 'sample comment',
     *    post: '<whatever_id_was_used>' 
     * }
     * 
     */
  }
});

Post.onChange(({ event, changed }) => {
  if (event === 'insert') {
    // trigger insert 1st comment, when 1st post is inserted
    const postId = changed[0].id;
    Comment.insert({
      name: 'sample comment',
      post: postId,
    });
  }
});

// setup first post
Post.insert({
  name: 'sample post',
  comments: [],
});
```

The log when `Comment` is `onLoaded` versus what is passed in `changed` in the `onChange` hook when inserting have different foreign keys for `Post`.

**Comment by hieunc229** [comment]
Thank you for the details. I blame for the current design that makes it a bit confusing. 

In your example, it'd be better to get the object (`Comment` in this case) using `Comment.get({ id })` so it will return a proper record info

```js
Comment.onChange(({ event, changed }) => {
  // check value of newly inserted comment
  if (event === 'insert') {
    console.log(Comment.get({ id: changed[0].id })); // originally was `changed[0]`
    /** This will print something like this:
     * {
     *    name: 'sample comment',
     *    post: '<whatever_id_was_used>' 
     * }
     * 
     */
  }
});
```

**Comment by hieunc229** [comment]
Please let me know if the problem is still persist
