### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by guatedude2** [vasern/vasern#34]
Feature request:
It would be nice to support JSON natively, currnetly I have to store the data as string and convert it to JSON on the fly, it would be nice to support this natively.

**Comment by hieunc229** [comment]
Hey @Alejandro, thanks for the suggestion. The next version will be a native NoSQL, which is schema-less. It stores object, array natively. I hope it is what you mean

**Comment by guatedude2** [comment]
Yes that’s even better. Thanks for the prompt response. Looking forward to the next version.
