### ISSUE TITLE
int are still saved as strings

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#35]
I have wondered why though i declare the type as int i still get the number as string from db.

So i have looked in the source code and i think i found the mistake under Parser.js and Parser.parseValue().

My new code of this function

et dataType;
    let type = inputType;
    let results;
    let splitted;

    if (type.indexOf("[]") !== -1) {
      dataType = "list";
      type = type.replace("[]", "");
    } else if (type.indexOf("#") !== -1) {
      dataType = "ref";
      type = type.replace("#", "");
    } else {
      if (type.indexOf("?") !== -1) {
        type = type.replace("?", "");
        dataType = type;
      }
      dataType = type;
    }

      //replace questinmark, so type can be itendified correctly
      
      //check if value exists and is not empty string but type is string
      if (val) {
        if (val === "") {
          if(dataType === "string"){
            return val && val.replace ? val.replace(/\u00A0n/g, "\n") : "";
          }else{
            return null;
          }
        } else{
          //look if val is defined
          switch (dataType) {
            case "string":
              return val && val.replace ? val.replace(/\u00A0n/g, "\n") : "";
            case "int":
              return parseInt(val, 10);
            case "double":
              return parseFloat(val);
            case "boolean":
              return val === "1";
            case "datetime":
              return new Date(parseInt(val, 10));
            case "ref":
              return val;
            case "list":
              splitted = val.split(LBreak);
              results = new Array(splitted.length);
              splitted.forEach((value, i) => {
                results[i] = Parser.parseValue(type, value);
              });
              return results;
            default:
            console.log(dataType);
              return val;
          }
        }
    }
    return null;

I have tested it and had no issues yet.
(i know it is kind of a pull request...)

**Comment by hieunc229** [comment]
Hey @apppro123, thanks for reporting the issue. I'll double-check and make an update

**Comment by hieunc229** [comment]
Hi Noah, I tested (on React Native 0.60.4) in numbers from positive, negative, 0 as `int` but couldn't find the case that caused the issue. Do you mind to have an example?

**Comment by apppro123** [comment]
Sorry i just saw that I have described the false issue (but I think I have solved it right). The main problem was, that it doesnt replaced the question mark in type variable so all types with questionmark went into default and I noticed it, when it didnt convert integer variables.

**Comment by hieunc229** [comment]
That's true, I forgot the case where data type is optional, in this case `?int`. I'll make an update.
Thanks for spotting the issue Noah @apppro123
