### ISSUE TITLE
Object and Array data types

### ISSUE THREAD

**Issue by kailashvele** [vasern/vasern#36]
Hi, 

There are use cases when there is a need for storing the whole object. Where the object is received from API and we are not completely aware what kind of data types each key might have with it.

Is there any option for storing Object Data type? I couldn't see it in the documentation.

For eg. 

`
const VasernDB = new Vasern({ 
  schemas: [{
    name: "Users",
    props: {
      data: "object"
    }
  }]
});
`

**Comment by hieunc229** [comment]
Welcome to the group, Kai!

At the moment, Vasern doesn't support `object` type. You can either (1) define a schema for that object and then [add a reference](https://vasern.com/docs/supported-data-types#todo-use-case), or (2) store as a string using `JSON.stringify`, thn parse it back as an object using `JSON.parse`.

**Comment by kailashvele** [comment]
Thank You @hieunc229 , Yes by stringifying it can be used.

But are there any plans to add them by default in the future?

**Comment by hieunc229** [comment]
@kailashvele No worries! Yes, it will definitely support the object and array natively.
I'm working to release the version soon (in a few months time)

**Comment by kailashvele** [comment]
oh Great ! Thanks @hieunc229 .
