### ISSUE TITLE
Cannot read property 'perform' of undefined

### ISSUE THREAD

**Issue by iMokhles** [vasern/vasern#41]
i issue while using this awesome package for the first time ( i wasn't able to fix it at all )
here's my setup

- Stracture

![Capture d’écran 2019-10-06 à 21 00 08](https://user-images.githubusercontent.com/1247248/66274208-6899a800-e87c-11e9-90ec-d9ca1c2f8d02.png)

- Initialization 

![Capture d’écran 2019-10-06 à 21 00 13](https://user-images.githubusercontent.com/1247248/66274211-6e8f8900-e87c-11e9-99a9-15ced75cb4c4.png)

![Capture d’écran 2019-10-06 à 21 00 19](https://user-images.githubusercontent.com/1247248/66274212-73ecd380-e87c-11e9-8651-af7b726337c6.png)

- Usage

![Capture d’écran 2019-10-06 à 21 00 55](https://user-images.githubusercontent.com/1247248/66274229-9848b000-e87c-11e9-983e-07d8b0f9589c.png)

i keep getting `Cannot read property 'perform' of undefined`

![Capture d’écran 2019-10-06 à 21 02 32](https://user-images.githubusercontent.com/1247248/66274234-a72f6280-e87c-11e9-8bbe-625992b1fcc0.png)

can you help me ?

**Comment by iMokhles** [comment]
Okey i was able to fix this issue by setting the `Model name` same as`Schema name`

**From this**
```
export default class UserModel {
    name = "Users";
    // Note: no "id" in "props", it will be automatically ignored otherwise
    props = {
        userId: "string",
        name: "string",
        email: "string",
        phone: "string",
        lang_code: "string",
        bio: "string",
        site: "string",
        country: "string",
        birth_date: "string",
        gender: "string",
        show_phone: "boolean",
        show_name: "boolean",
        is_blocked: "boolean",
        access_token: "string",
        token_type: "string",
        expires_in: "string",
        created_at: "string",
        isCurrentUser: "boolean",
    }
}
```

**to this**
```
export default class Users {
    name = "Users";
    // Note: no "id" in "props", it will be automatically ignored otherwise
    props = {
        userId: "string",
        name: "string",
        email: "string",
        phone: "string",
        lang_code: "string",
        bio: "string",
        site: "string",
        country: "string",
        birth_date: "string",
        gender: "string",
        show_phone: "boolean",
        show_name: "boolean",
        is_blocked: "boolean",
        access_token: "string",
        token_type: "string",
        expires_in: "string",
        created_at: "string",
        isCurrentUser: "boolean",
    }
}
```

**Comment by hieunc229** [comment]
Hey @iMokhles, good one. I'll be happy to help in case you have other issue :)
