### ISSUE TITLE
Get all data, return raw string

### ISSUE THREAD

**Issue by pnthach95** [vasern/vasern#5]
I created a scaning-code (barcode, QR...) app using Vasern to save codes.
When I get all records in componentDidMount, it returns raw values first. My FlatList can't render properly.
- CodeModel:
```
export class CodeModel {
  name = 'Codes';
  props = {
    time: 'string',
    data: 'string',
    type: 'string'
  }
}
```

- Console log:

![screen shot 2018-11-12 at 4 05 07 pm](https://user-images.githubusercontent.com/31266357/48337202-e49f6600-e694-11e8-9fbe-74df6c1fb7f7.png)

![screenshot_20181112-155909](https://user-images.githubusercontent.com/31266357/48337308-30eaa600-e695-11e8-9788-937b5cf5ed4a.png)

When I scanned a barcode, it re-rendered properly.

![screenshot_20181112-155930](https://user-images.githubusercontent.com/31266357/48337450-8757e480-e695-11e8-80d3-d119fd813e22.png)

How can I fix it?
My project: https://github.com/pnthach95/ScanCodeRNApp
Dependencies:
```
react-native: 0.57.4
vasern: 0.2.83
```

**Comment by hieunc229** [comment]
Hi @pnthach95, it shows raw string mean data is loaded but have not serialized yet. You can add a `onLoaded` listener and use setState within the callback. For example:

[Line 21, componentDidMount - History.js](https://github.com/pnthach95/ScanCodeRNApp/blob/master/App/Components/History.js#L21)

```javascript
Codes.onLoaded(() => {
   let data = Codes.data();
   this.setState({ list: data });
});
```

Just a note, the project is still in development at the moment. The stable version will be release in a few 2-4 weeks, though most of APIs won't be changed.

**Comment by pnthach95** [comment]
It worked. Thanks.
Close issue.
