### ISSUE TITLE
does vasern supported Bulk Insert?

### ISSUE THREAD

**Issue by zxccvvv** [vasern/vasern#56]
Hi, i want to insert object in array, but i don't know what is the best way to do it

let say i have this array :
```
[
  {id : '1', name : 'foo', shortName : 'fo', img : 'url', telp : '123'},
  {id : '2', name : 'bar', shortName : 'ba', img : 'url2', telp : '1234'},
]
```

i want to insert those object in vasern, and below is my code:

```
//data var is those array
data.map((item)=>{
  Db.MyModel.insert({
    id: item.id,
    name: item.name,
    shortName: item.shortName,
    img: item.img,
    telp: item.telp
  })
})
DB.MyModel.onLoaded(()=>{
  let data = DB.MyModel.data()
  console.log('Log Queries' , data)
})
```

but i cannot get the value immediately when i console.log the Model with above code,
any suggestion?

**Comment by hieunc229** [comment]
Hey @zxccvvv, have you tried to use the `perform` method? Here is an example
```js
MyModel.perform(db => {
    data.forEach(item => {
        db.insert(item)
    });
});
```

You can read about [perform on Basic CRUD operations](https://vasern.github.io/docs/basic-crud-operation#perform-multiple-operations)

Let me know in case you still unable to use it

**Comment by zxccvvv** [comment]
I think i can use it
but there's some way to access those data when `perform` has finished?

**Comment by hieunc229** [comment]
I get what you mean now. There are 2 ways you can do it:

1. Use the returned value of `insert` method. For example:

```js
// insertedItems are what will be inserted into database
let insertedItems = MyModel.insert(items);
```
_Note that you can pass an array into `insert`. But this method returns data before it is written into the database. To get items after it is written, use the next method._

2. Use event listener `onInsert(callback)` (or `onChange` or any other event as delete, update). This way, any data inserted will be captured, and pass through your `callback`. For example:

```js
MyModal.onInsert(data => {
   console.log(data)
})
```

You can read about [event listener on Vasern](https://vasern.github.io/docs/event-listeners)

**Comment by zxccvvv** [comment]
hi @hieunc229 sorry for late response,

i just think this code for inserting one row, but i need to get an event when all data is inserted (multiple insert)

> ```js
> // insertedItems are what will be inserted into database
> let insertedItems = MyModel.insert(items);
> ```
> 1. Use event listener `onInsert(callback)` (or `onChange` or any other event as delete, update). This way, any data inserted will be captured, and pass through your `callback`. For example:
> 
> ```js
> MyModal.onInsert(data => {
>    console.log(data)
> })
> ```

does `perform` has callback when it task has finished?
something like

```
MyModel.perform((db) => {
    data.forEach(item => {
        db.insert(item)
    });
},(fail/done)=>doSomethingWhenAllDataInserted());
//or with promise
.then((fail/done)=>doSomethingWhenAllDataInserted())
```

**Comment by hieunc229** [comment]
No worries @zxccvvv!

There no callback at the moment for inserting data. I'm just curious if there is any reason you can't you `event listener`? (Maybe I could use it to improve the library in the future)

**Comment by zxccvvv** [comment]
because using this code:

```
data.map((item)=>{
  Db.MyModel.insert({
    id: item.id,
    name: item.name,
    shortName: item.shortName,
    img: item.img,
    telp: item.telp
  })
})
DB.MyModel.onLoaded(()=>{
  let data = DB.MyModel.data()
  console.log('Log Queries' , data)
})
```

the log tell me `onLoaded` running first (log: `[ ]`) before the insert method, so i think the `onLoaded` event fire before the insert has done

**Comment by hieunc229** [comment]
There are also other event listener. For example `onInsert`, `onChange`, etc. Besides, it'd be better to insert within `onLoaded` listener.

Try this example:
```js
DB.MyModel.onChange(data => {
    console.log(data)
})

DB.MyModel.onLoaded(()=>{
    data.map((item)=>{
    Db.MyModel.insert({
        id: item.id,
        name: item.name,
        shortName: item.shortName,
        img: item.img,
        telp: item.telp
    })
    })
  let data = DB.MyModel.data()
  console.log('Log Queries' , data)
})
```

**Comment by zxccvvv** [comment]
still with your code, the console.log show `Log Queries, [ ]` then running the insert method,

here's my console for better understand:
![image](https://user-images.githubusercontent.com/19633881/78527525-52f34400-7807-11ea-82ac-738916ce9a78.png)

**Comment by hieunc229** [comment]
My bad, the `Log query` shouldn't be there, since we use onChange `listner`. Instead:

```js
DB.MyModel.onChange(data => {
    console.log(data)
})

DB.MyModel.onLoaded(()=>{
    data.forEcah((item)=>{
        Db.MyModel.insert({
            // id: item.id, id will be ignore and generate a new one
            name: item.name,
            shortName: item.shortName,
            img: item.img,
            telp: item.telp
        })
    })
})
```

**Comment by zxccvvv** [comment]
thank you @hieunc229 ,

last question,

how do i get all data in vasern?
does `Db.MyModel.data()` enough to do that?

**Comment by hieunc229** [comment]
From your example, using `.data()` will return all data from `Db.MyModel`. 
In case you want to get all data from all collection, you will need to use `.data()` for each collection/model
