### ISSUE TITLE
Relationship table

### ISSUE THREAD

**Issue by di1606** [vasern/vasern#66]
Can we make a pivot table? I didn't find it in the documentation.

- If that's the case, how can we do it ? 

here is an exemple :

```
users
    id - integer
    name - string

roles
    id - integer
    name - string

role_user
    user_id - integer
    role_id - integer
    text - string
```

**Comment by hieunc229** [comment]
Hey @di1606, 

I don't understand the term "pivot table". Can you explain it?

(Look to me like the `role_user` is kind of a relationship tablet for `users` and `roles`?)

**Comment by di1606** [comment]
yes, I'm referring to a relationship tablet

**Comment by hieunc229** [comment]
Have you tried using reference type data type?

For example:

```js

// Note that the document/table will generate `id` automatically, [so no `id` field](https://vasern.github.io/docs/write-schema-setup-vasern#write-schema)

users
    name - string

roles
    name - string

role_user
    user - #users
    role - #role
    text - string
```

Then with the [Vasern instance](https://vasern.github.io/docs/write-schema-setup-vasern#create-vasern-instance), you can you `list`

For example

```js

const db = new Vasern(...);
let data = db.list("role_user");
```

I haven't tested the code but it should be. Let me know how you go

**Comment by di1606** [comment]
Thank you. It works.
