### ISSUE TITLE
Unable to get data

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#7]
var TodoSchema = {
            name: "Todos",
            props: {
                name: "string",
                note: "?string",
                completed: "boolean"
            },
        };
        
        const VasernDB = new Vasern({
            schemas: [TodoSchema],
            version: 1
        });
        
        const { Todos } = VasernDB;
        
        
        var item1 = Todos.get({ name: "Setup database for React Native" });
        console.log(item1);
        Todos.remove(item1);
        console.log(Todos._data);
        console.log(Todos.available);

At the moment i cannot perform for example 
Todos.data() or Todos.get({ name: "Setup database for React Native" }) or Todos.remove() doesnt work!!

it runs when i want to get Todos._data, but i just get an empty list but when i just want to get Todos i see under the object, that there should be 7 items in the list
and also Todos.available is false but in the object Todos it is true!?

**Comment by hieunc229** [comment]
I also have update issue name with a more meaning description!

**Comment by apppro123** [comment]
Sorry that i have to reopen this issue, but i just noticed, that i still cannot get the data with .data(). But unter the object are a lot of element (under _data)!
Maybe in the functin data() there is a false syntax (maybe the "this" is not related to the object or so).

**Comment by hieunc229** [comment]
Hi @apppro123, have you try to use ‘onLoaded’?

Here is an example https://github.com/vasern/vasern/issues/5#issuecomment-437836842

**Comment by apppro123** [comment]
Now it is working! Is this because the db is not loaded after app starts (i want to access data() in componentDidMount()) ?
And why is it showing the right data in the object?

**Comment by hieunc229** [comment]
Raw data is loaded before the app started. It will be serialised after the app started, then become available to use.

On your componentDidMount(), you can use ‘.data()’ within ‘.onLoaded’ callback.

I didn’t get what you mean by ‘showing data in the object’. Can you explain a bit more? Thanks!

**Comment by hieunc229** [comment]
If you use__.data()__ inside __onLoaded__ event, does it still show an empty result?

Use __.data()__ will ensure data is properly serialised correctly.

**Comment by apppro123** [comment]
Inside the onLoaded it is working correctly. But it is strange that data()  doesnt work without onLoaded but if i just show the object (console.log(Calendar)) there under _data it shows the right array and that is also without onLoaded!?

**Comment by hieunc229** [comment]
The reason `.data()` not working without `.onLoaded` because when the app started, it fetches raw data and saves it in `_data`. Then it will serialize records one by one. When all records are serialized, `.data()` will be able to return records.

So it is safe to use `.data()`. Otherwise, if the serialize records is not completed, you might get unserialized records.

I would recommend you to use `.data()` inside `.onLoaded` because once the database size grows big. The serialize process will take more time. You will not receive correct records using `_data`
