### ISSUE TITLE
Insertion problem 

### ISSUE THREAD

**Issue by di1606** [vasern/vasern#73]
I have a problem when I insert the data to the "assignedTo" attribute. At the moment the data are inserted, it work. But if I reload the application the data of the attribute "assignedTo" disappears. 

here is my entry: 
```
const budget = Budgets.insert({
            currency,
            start_date: startDate,
            end_date: endDate,
            created_at: nowStr,
            assignedTo: account
        })[0];
```
the display I have in my log when inserting
`[Sat Jul 18 2020 12:13:14.836]  LOG      [{"assignedTo": {"created_at": "18-07-2020", "id": "5f12cb2cgeCHGxjx0009cF9e", "name": "grf"}, "created_at": "18-07-2020", "currency": "CHF", "end_date": "18-08-2020", "id": "5f12cb2cbLpSb6I4000DIDR4", "start_date": "18-07-2020"}]`

and here are the contents after reloading the application

`[Sat Jul 18 2020 12:13:27.476]  LOG      [{"created_at": "18-07-2020", "currency": "CHF", "end_date": "18-08-2020", "id": "5f12cb2cbLpSb6I4000DIDR4", "start_date": "18-07-2020"}]`

we notice that the ID is different and the attribute "assignedTo" doesn't exist anymore. 

this is the budget model 

```
export default class BudgetModel {
    name = "Budgets";

    props = {
        currency: 'string',
        start_date: 'string', // I know I can put some type datetime
        end_date: 'string', // I know I can put some type datetime
        created_at: 'string' // I know I can put some type datetime
    }
    assignedTo = "#Accounts";
}
```

**Comment by hieunc229** [comment]
I guess the problem is `assignedTo` should be inside `props` in the `BudgetModel`.

```js
export default class BudgetModel {
    name = "Budgets";

    props = {
        currency: 'string',
        start_date: 'string', // I know I can put some type datetime
        end_date: 'string', // I know I can put some type datetime
        created_at: 'string' // I know I can put some type datetime,
        assignedTo: "#Accounts"
    }
}
```

Please let me know how it goes. If you still have problem, I'll check it later today

**Comment by di1606** [comment]
Great it works,

it should be specified in the documentation so as not to induce error 

https://vasern.github.io/docs/write-schema-setup-vasern
<img width="496" alt="Capture d’écran 2020-07-18 à 13 20 50" src="https://user-images.githubusercontent.com/27860198/87851515-c2de9380-c8f9-11ea-8c48-cb2a35f0cf2a.png">

**Comment by hieunc229** [comment]
Hey @di1606, I didn't notice the mistake. Thanks for pointing this out :)
