### ISSUE TITLE
Support default Value?

### ISSUE THREAD

**Issue by zxccvvv** [vasern/vasern#75]
Hi, does Vasern support default value?

i need to handle if user is currently install or not,

my usecase something like:

- IF user is first install, show introduction screen, else skip introduce screen

**Comment by hieunc229** [comment]
Hey @zxccvvv, Vasern doesn't support default value.

Can you explain the use case a bit more?

Besides, can you specify a default value in your code instead of using default value from Vasern? 
Or maybe check if the value is `undefined`?

**Comment by zxccvvv** [comment]
hi @hieunc229 

actually i've created my model something like this:

`DB.js`
```
import Vasern from 'vasern';
import { CheckInstallState } from './Model';

modelSchema = [
  CheckInstallState
];

export default new Vasern({ schemas: modelSchema});
```

`Model.js`
```
export class CheckInstallState {
	name = 'CheckInstallState'
	props = {
    firstInstall:'boolean', // here i want to set default true
	}
}
```

i want to set default value of my model to true, so everytime an app is opened, i want to check if `firstInstall` is true or not,
so when i see `firstInstall` is true, i want to show `On-Boarding` screen and set `firstInstall` to false, meanwhile when user open the app more than one, the `firstInstall` value should be false forever

**Comment by hieunc229** [comment]
Hey @zxccvvv, 

I think it'd be much different when having a default value (since it need to wait until the data is loaded).
I'd do as following:

```js
// Model.js
export class CheckInstallState {
    name = 'CheckInstallState'
    props = {
        onboardingVisible: 'boolean',
    }

    isInstalled() {
        return !!this.length();
        // Maybe, if length === 0, insert a record to mark as onboarded
    }
}
```

Then whenever the app startup, I'd check it as

```js
// import db from "./DB"

...
    componentDidMount() {
        db.onLoaded(() => {
            let firstInstall = db.CheckInstallState.isInstalled();

            // if firstInstall === true => show screen
            // else => ignore
        });
    }
...

```

Is it not possible on your case?
Sorry that I'm caught up with other projects. At the moment, I'll add more feature only necessary

**Comment by zxccvvv** [comment]
It's sound good to implement your code above,

ill try and closed the issue ATM, thank you @hieunc229

**Comment by zxccvvv** [comment]
hi @hieunc229 ,

I don't know why vasern doesn't inserting data:

```
...
componentDidMount(){
    //Check if App is first insalled
    DB.CheckInstallState.onChange(e=>{
      console.log('e', e)
    })
    DB.onLoaded(()=>{
      const isFirstInstall = DB.CheckInstallState.isFirstInstalled()
      console.log('isFirstInstall', isFirstInstall)
      if(isFirstInstall){
        DB.CheckInstallState.insert({showOnBoarding:false})
      }
      return this.setState({isFirstInstalled:isFirstInstall})
    })
  }
...
```

```
export class CheckInstallState {
	name = 'CheckInstallState'
	props = {
    showOnBoarding:'boolean',
  }
  
  isFirstInstalled() {
    console.log('data', this.data())
    return this.length()===0
  }
}
```

ini `ComponentDidMount()` `console.log('isFirstInstall', isFirstInstall)` always outputing true when i open the app

**Comment by hieunc229** [comment]
Alrighty!

I figured out it was a bug. Because when inserting an item, it will check each property if it's valid.
The bug was, when checking `showOnBoarding`, the value was false, somehow it was invalid.

I'll make a fix soon.

For now, if you still want to go ahead, changed `showOnBoarding` type to `string`. Then when inserting, use a string. For example:

```js
...
DB.CheckInstallState.insert({showOnBoarding: `installed`})
...
```

**Comment by zxccvvv** [comment]
@hieunc229 
Thank you for quick reply and fixed
Appreciated

**Comment by hieunc229** [comment]
You're welcome @zxccvvv!
