### ISSUE TITLE
(security) Does the data file accessible by other apps?

### ISSUE THREAD

**Issue by apppro123** [vasern/vasern#8]
How secure is this database?
Is it accessible by other apps?

**Comment by hieunc229** [comment]
Hey @apppro123, the database is saved internally, only accessible by your app. Other apps won't be able to access it.

**Comment by apppro123** [comment]
Thank you for your fast response!

**Comment by hieunc229** [comment]
No worries @apppro123. I am currently working on version [0.3.0-rc](https://github.com/vasern/vasern/tree/0.3.0-rc) which has a bit of data structure changes, more query features including `paging`, `sort`, `limit`, `include` (similar to join in sql), etc. Hopefully will be available end of this month :) 

By the way, I made an update for this issue title to be more descriptive (it will helps other search it quickly).

**Comment by apppro123** [comment]
Thank you: i'm not good at making titles ;)

**Comment by arnaud-zg** [comment]
So it is kind a like local storage for web browser right ?

**Comment by hieunc229** [comment]
@arnaud-zg Yes, it is local storage (or database) but only for [React Native](https://facebook.github.io/react-native/).

**Comment by hieunc229** [comment]
I will close this issue since it has been resolved. Also, feel free to reopen or create a new one again
