### ISSUE TITLE
Broken Links in Getting Started Section

### ISSUE THREAD

**Issue by KrisGilicze** [vasern/vasern#98]
Just quickly fixing the links in the Readme.md 

- Write Schema, Setup Vasern
- Basic CRUD operations

**Comment by KrisGilicze** [comment]
Just realized I don't have permissions to create a PR, but here's the code
`

- [Install Vasern](docs/install-vasern.md)
- [Supported Data Types](docs/supported-data-types.md)
- [Write Schema, Setup Vasern](docs/write-schema.md)
- [Basic CRUD operations](docs/basic-crud-operations.md)
- [Queries](docs/queries.md)
`

**Comment by hieunc229** [comment]
Thanks, @KrisGilicze. I updated the links
